# ======================================================
# Streamlit App Configuration (by Toba Jordi Naibaho)
# ======================================================

[theme]
base="light"
primaryColor="#228B22"         # Hijau alami seperti padi 🌾
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#1E1E1E"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
toolbarMode = "minimal"

[logger]
level = "info"
